/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company.view.comprador;

import com.company.controller.comprador.CompradorController;
import com.company.controller.comprador.IComprador;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUS
 */
public class FrmAdminComprador extends javax.swing.JFrame {

    IComprador service;

    /**
     * Creates new form FrmAdminComprador
     */
    public FrmAdminComprador() {
        initComponents();
        service = new CompradorController();
        loadData();
        this.setLocationRelativeTo(null);
    }

    public void loadData() {
        try {
            String[] headers = new String[]{"Id", "Nombre",
                "Apellido", "Email", "Telefono", "Numero registro"};
            DefaultTableModel tb = new DefaultTableModel(service.getAll(), headers);
            this.tblComprador.setModel(tb);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al leer la base de datos [" + ex.getMessage() + "]");
        }
    }

    public static void entraMouseInput(JTextField txt, String text) {
        if (txt.getText().equals(text)) {
            txt.setText("");
        }

    }

    public static void saleMouseInput(JTextField txt, String text) {
        if (txt.getText().isEmpty()) {
            txt.setText(text);
        }

    }

    public String[] getData() {//contiene el arreglo que se envia para el controller
        String[] data = {
            this.txtId.getText(),
            this.txtNombre.getText(),
            this.txtApellido.getText(),
            this.txtEmail.getText(),
            this.txtTelefono.getText(),};
        return data;
    }

    public void setData(String[] data) {//llena los campos con los datos que le envia la DB
        this.txtId.setText(data[0]);
        this.txtNombre.setText(data[1]);
        this.txtApellido.setText(data[2]);
        this.txtEmail.setText(data[3]);
        this.txtTelefono.setText(data[4]);
    }

    public void clearInputs() {
        String[] data = {"Ingrese la cedula", "Ingrese el nombre", "Ingrese el apellido", "Ingrese el email", "Ingrese el telefono"};
        setData(data);
    }

    public boolean verificarVacio() {
//        boolean[] estado = {false, false, false, false, false};
        short cont = 0;
        String[] data = getData();
        String[] comparar = {"Ingrese la cedula", "Ingrese el nombre", "Ingrese el apellido", "Ingrese el email", "Ingrese el telefono"};
        for (int i = 0; i < 5; i++) {
            if (!data[i].equals(comparar[i]) && !data[i].equals(" ")) {
//                estado[i] = true;
                cont++;
            }

        }
//        for (boolean verifico : estado) {
//            if (verifico == true) {
//                
//            }
//        }
        return cont == 5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComprador = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N

        tblComprador.setForeground(new java.awt.Color(0, 136, 145));
        tblComprador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblComprador.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblComprador);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 180, 580, 360));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 136, 145));
        jLabel1.setText("Cedula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 88, 122));
        jLabel2.setText("Administracion de Comprador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 520, 80));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 136, 145));
        jLabel3.setText("Lista de compradores");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 240, 40));

        txtId.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 136, 145));
        txtId.setText("Ingrese la cedula");
        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 222)));
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 240, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 136, 145));
        jLabel4.setText("Creacion de comprador");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 136, 145));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, 30));

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 136, 145));
        txtNombre.setText("Ingrese el nombre");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 222)));
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 240, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 136, 145));
        jLabel6.setText("Apellido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 50, 30));

        txtApellido.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 136, 145));
        txtApellido.setText("Ingrese el apellido");
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 222)));
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 240, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 136, 145));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 50, 30));

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 136, 145));
        txtEmail.setText("Ingrese el email");
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 222)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 240, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 136, 145));
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 50, 30));

        txtTelefono.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 136, 145));
        txtTelefono.setText("Ingrese el telefono");
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 222)));
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 240, 30));

        btnCrear.setBackground(new java.awt.Color(0, 88, 122));
        btnCrear.setForeground(new java.awt.Color(231, 231, 222));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 100, 30));

        btnBuscar.setBackground(new java.awt.Color(231, 231, 222));
        btnBuscar.setForeground(new java.awt.Color(0, 88, 122));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(231, 231, 222));
        btnEliminar.setForeground(new java.awt.Color(0, 88, 122));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        if (verificarVacio()) {
            JOptionPane.showMessageDialog(this, service.addC(getData()));
            loadData();

        } else {
            JOptionPane.showMessageDialog(this, "Llene todos campos");
        }
        clearInputs();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String[] data = service.find(getData()[0]);
        if (data != null && data[0] != null) {
            setData(data);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado en la base de datos");
            this.clearInputs();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (verificarVacio()) {
            JOptionPane.showMessageDialog(this, service.deleteC(getData()[0]));
            loadData();

        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado en la base de datos");
        }
        clearInputs();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        // TODO add your handling code here:
        entraMouseInput(txtId, "Ingrese la cedula");
    }//GEN-LAST:event_txtIdFocusGained

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        // TODO add your handling code here:
        saleMouseInput(txtId, "Ingrese la cedula");
    }//GEN-LAST:event_txtIdFocusLost

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        // TODO add your handling code here:
        entraMouseInput(txtNombre, "Ingrese el nombre");
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
        saleMouseInput(txtNombre, "Ingrese el nombre");
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusGained
        // TODO add your handling code here:
        entraMouseInput(txtApellido, "Ingrese el apellido");
    }//GEN-LAST:event_txtApellidoFocusGained

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        // TODO add your handling code here:
        saleMouseInput(txtApellido, "Ingrese el apellido");
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        entraMouseInput(txtEmail, "Ingrese el email");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        saleMouseInput(txtEmail, "Ingrese el email");
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
        // TODO add your handling code here:
        entraMouseInput(txtTelefono, "Ingrese el telefono");
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        // TODO add your handling code here:
        saleMouseInput(txtTelefono, "Ingrese el telefono");
    }//GEN-LAST:event_txtTelefonoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminComprador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComprador;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
